### ISSUE TITLE
Parsing of JSON-LD breaks when the JSON is followed by a semicolon

### ISSUE THREAD

**Issue by JonasOlson** [scrapinghub/extruct#109]
I don't know if having the JSON being followed by a semicolon constitutes valid JSON-LD, but I have encountered it in the wild.

Running extruct on the following works fine:

```
<script type="application/ld+json">
{}
</script>
```

However, this breaks:

```
<script type="application/ld+json">
{};
</script>
```

The error message looks like this:

```
Failed to extract json-ld, raises Extra data: line 2 column 3 (char 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/extruct/jsonld.py", line 34, in _extract_items
    data = json.loads(script, strict=False)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 3 (char 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/extruct/_extruct.py", line 101, in extract
    output[syntax] = list(extract(document, base_url=base_url))
  File "/usr/local/lib/python3.6/dist-packages/extruct/jsonld.py", line 26, in extract_items
    for items in map(self._extract_items, self._xp_jsonld(document))
  File "/usr/local/lib/python3.6/dist-packages/extruct/jsonld.py", line 25, in <listcomp>
    item
  File "/usr/local/lib/python3.6/dist-packages/extruct/jsonld.py", line 38, in _extract_items
    HTML_OR_JS_COMMENTLINE.sub('', script), strict=False)
  File "/usr/lib/python3.6/json/__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 3 (char 3)
```

Extruct version 0.7.2; Python version 3.6.7; Ubuntu 18.04.2

**Comment by Gallaecio** [comment]
This should be covered by #45.
