### ISSUE TITLE
Latest release on PyPi (0.16.0) breaks with lxml>5.1.0: import extruct throws ImportError: cannot import name '_ElementStringResult'

### ISSUE THREAD

**Issue by mfhepp** [scrapinghub/extruct#231]
The latest version available from PyPi (0.16.0) breaks when used with `lxml` greater than 5.1.0.

The reason is that `lxml` seems to have dropped some internal objects, like `lxml.etree._ElementStringResult`, which are imported in `xmldom.py` in line 9 (in 0.16.0).

A temporary fix is to use  lxml<=5.1.0 in your environment.

```
Traceback (most recent call last):
  File "/usr/app/src/./foo.py", line 13, in <module>
    import extruct
  File "/opt/conda/lib/python3.12/site-packages/extruct/__init__.py", line 1, in <module>
    from ._extruct import SYNTAXES, extract
  File "/opt/conda/lib/python3.12/site-packages/extruct/_extruct.py", line 9, in <module>
    from extruct.dublincore import DublinCoreExtractor
  File "/opt/conda/lib/python3.12/site-packages/extruct/dublincore.py", line 6, in <module>
    from extruct.utils import parse_html
  File "/opt/conda/lib/python3.12/site-packages/extruct/utils.py", line 5, in <module>
    from extruct.xmldom import XmlDomHTMLParser
  File "/opt/conda/lib/python3.12/site-packages/extruct/xmldom.py", line 9, in <module>
    from lxml.etree import (
ImportError: cannot import name '_ElementStringResult' from 'lxml.etree' (/opt/conda/lib/python3.12/site-packages/lxml/etree.cpython-312-aarch64-linux-gnu.so). Did you mean: '_ElementUnicodeResult'?
```

**Notes:**
1. I am using a `conda` environment with `extruct` installed via `pip`, but I think the main reason is that the latest version available on PyPi version is not compatible with the latest `lxml` release.
2. This might be already addressed in the lates development version, but will likely hit many people who are forced to install with `pip`.

**Comment by mfhepp** [comment]
I just noticed that this is a duplicate of #217, fixed by https://github.com/scrapinghub/extruct/commit/9e0179be7721af29caab6bb29bd40e1a77f9ed2c 

But I keep it open so that Google will point people to this as long as the PyPi version has not been updated.

A new release will most likely fix this issue.
